# Site settings
gems:
  - jekyll-mentions
  - jekyll-sitemap

owners:
  - name: "Mostofa Ansary"
    url:
  - name: "Hermilo Calderon"
    url:
  - name: "Michael MacCallum"
    url: "https://stackoverflow.com/users/716216/0x7fffffff?tab=profile"
  - name: "Andrew Owen"
    url: "http://www.junglecoder.com"
  - name: "John Zachariah"
    url:

project:
  title: "Eagleslist"
  description: "a used textbook buying and trading service for FGCU students"

title: 5Bit
subtitle: "A textbook trading service for FGCU students."
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://5-bit.github.io" # the base hostname & protocol for your site
domain: "5-Bit.GitHub.io"
twitter_username:
github_username:  "5-bit"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
