# Site settings
gems:
  - jekyll-mentions
  - jekyll-sitemap

owners:
  - name: "Mostofa Ansary"
    url:
  - name: "Hermilo Calderon"
    url:
  - name: "Michael MacCallum"
    url: "https://stackoverflow.com/users/716216/0x7fffffff?tab=profile"
  - name: "Andrew Owen"
    url: "http://www.junglecoder.com"
  - name: "John Zachariah"
    url:

project:
  title: "Eagleslist"
  description: "a used textbook buying and trading service for FGCU students"

title: 5Bit
subtitle: "A textbook trading service for FGCU students."
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://5-bit.github.io" # the base hostname & protocol for your site
domain: "5-Bit.GitHub.io"
twitter_username:
github_username:  "5-bit"

# Build settings
markdown: kramdown
